
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

// add module here
    logic clk_out;
    logic [3:0] id, date;
	freg_div_23 fre_23(
		.clk(CLK),
		.reset(~BTN[0]),
		.clk_out(clk_out)
	);
    student_id sid(
        .clk(clk_out),
        .reset(~BTN[0]),
        .id(id)
    );
	birthdate bd(
        .clk(clk_out),
        .reset(~BTN[0]),
        .date(date)
    );
	seven_segment s0(
    	.in(id),
    	.out(HEX0)
	);
	seven_segment s1(
    	.in(date),
    	.out(HEX1)
	);

//*******************************//

endmodule
