
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

// add module here
    logic clk_out;
    logic [2:0] sec_tens, min_tens;
    logic [3:0] sec_units, min_units;
	freg_div_23 fre_23(
		.clk(CLK),
		.reset(~BTN[0]),
		.clk_out(clk_out)
	);
    timer_h t1(
        .clk(clk_out),
        .reset(~BTN[0]),
        .min_tens(sec_tens),
        .hour_tens(min_tens),
        .min_units(sec_units),
        .hour_units(min_units)
    );
	seven_segment s0(
    	.in(sec_units),
    	.out(HEX0)
	);
	seven_segment s1(
    	.in(sec_tens),
    	.out(HEX1)
	);
	seven_segment s2(
    	.in(min_units),
    	.out(HEX2)
	);
	seven_segment s3(
    	.in(min_tens),
    	.out(HEX3)
	);

//*******************************//

endmodule
