
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

// add module here
    logic [3:0] q;
    logic y;
    counter_4bits counter(
        .clk(BTN[0]),
        .reset(~BTN[1]),
        .counter(q),
        .y(y)
    );
	seven_segment s7(
    	.in(q),
    	.out(HEX0)
	);

//*******************************//

endmodule
